# Código de conducta {#codigo-de-conducta}

## Nuestro compromiso

Nosotr\@s, miembr\@s, contribuidores y líderes nos comprometemos a hacer que la participación en nuestra comunidad sea una experiencia libre de acoso u hostigamiento para tod\@s, sin importar la edad, el cuerpo, cualquier tipo de impedimento visible o invisible, etnicidad, sexualidad, identidad u expresión de género, nivel de experiencia, educación, posición socio-económica, nacionalidad, apariencia personal, raza, religión o identidad y orientación sexual.

Nos comprometemos a actuar e interactuar con formas que contribuyan a una comunidad abierta, acogedora, diversa, inclusiva y saludable.

## Nuestros estándares

Ejemplos de un comportamiento que contribuye a un ambiente positivo para nuestra comunidad incluyen:

- Demostrar empatía y amabilidad para con las personas
- Ser respetuoso de otras opiniones, puntos de vistas y experiencias
- Dar y recibir agradecidamente el feedback constructivo
- Aceptar responsabilidades y disculparse para quienes sean afectados por nuestros errors, y aprendiendo de la experiencia
- Enfocarse en lo que es mejor no solo para nosotros como individuos, sino para toda la comunidad

Ejemplos de un comportamiento que no será aceptado incluyen:

- El uso de lenguaje o imágenes sexualizadas y cualquier tipo de atención o avance sexual
- Trolling, insultos o comentarios derogativos y cualquier tipo de ataque político o personal
- Acoso público o privado
- Publicación de información privada de terceros sin su permiso explícito
- Cualquier otra conducta que pueda ser razonablemente considerada inapropiada en un entorno profesional

## Responsabilidades de Ejecución

L\@s líderes de la comunidad son responsables de clarificar y hacer cumplir nuestros estándares de comportamiento aceptado y tomarán acciones correctivas apropiadas y justas en respuesta a cualquier comportamiento que consideren inapropiado, amenzante, ofensivo o dañino.

L\@s líderes de la comunidad tienen el derecho y la responsabilidad de remover, editar o rechazar comentarios, commits, código, ediciones de wiki, issues/tickets y cualquier otra contribución que no esté alineada a este Código de Conducta y comunicarán las razones de su acción moderadora de ser necesario.

## Alcance

Este Código de Conducta aplica a todos los espacios comunitarios y también aplica a un individuo que esté representando oficialmente a la comunidad en espacios públicos. Ejemplos de "representación" incluyen utilizar una dirección de e-mail oficial, postear via una cuenta oficial de redes sociales o actuando como un representante en un evento online u offline.

## Ejecución
Las instancias de comportamiento inaceptable, abusivo o acosador pueden ser reportadas a l\@s líderes de la comunidad responsables de ejecutar el Código de Conducta. Todas las denuncias serán revisadas e investigadas prontamente y justamente.

Tod\@s l\@s líderes de la comunidad están obligad\@s a respetar la privacidad y seguridad de quien reporte cualquier incidente.

## Medidas de Ejecución

L\@s líderes de la comunidad seguirán estas "Pautas de Impacto en la Comunidad" para determinar las consecuencias de cualquier acción que consideren viole este Código de Conducta:

### CORRECCIÓN
Impacto en la Comunidad: Uso de lenguaje inapropiado o cualquier otro comportamiento considerado no profesional o no bienvenido en la comunidad.

Consecuencia: Una advertencia escrita por pivado de parte de l\@s líderes de la comunidad, proveyendo claridad respecto a la naturaleza de la violación y una explicación de por qué el comportamiento fue inapropiado. Una disculpa pública puede ser solicitada.


### ADVERTENCIA
Impacto en la Comunidad: Una violación a través de un incidente único o una serie de acciones.

Consecuencia: Una advertencia con consecuencias por comportamiento continuo. No se permite la interacción con las personas involucradas, incluyendo interacciones no solicitadas para con quienes hacen cumplir el Código de Conducta, por un período especificado de tiempo. Esto incluye evitar interacciones en espacios comunitarios así como también canales externos como redes sociales. La violación de estos términos puede llevar a un ban temporal o permanente.


### BAN TEMPORAL
Impacto en la Comunidad: Una violación seria de los estándares de la comunidad, incluyendo un comportamiento inapropiado sostenido en el tiempo.

Consecuencia: Un ban temporal de cualquier tipo de interacción o comunicación pública para con la comunidad por un período específico de tiempo. No se permite ninguna interacción pública o privada con las personas involucradas, incluyendo interacciones no solicitadas para con quienes hacen cumplir el Código de Conducta. Violar estos términos puede terminar en un ban permanente.

#### BAN PERMANENTE

Impacto en la Comunidad: Demostración de patrones de violación de los estándares de la comunidad, incluyendo un comportamiento inapropiado sostenido en el tiempo, acoso de un individuo o agresión o menosprecio por cualquier clase de individuo.

Consecuencia: Un ban permanente de cualquier tipo de interacción con la comunidad.

## Atribución

Basado en https://pkgs.rstudio.com/bookdown/CODE_OF_CONDUCT.html que a su vez está basado en el Contributor Covenant, version 2.0, disponible en https://www.contributor-covenant.org/version/2/0/code_of_conduct.html.
