# Ideología

El término "ideología" fue formulado por el marqués de Tracy (un francés, filósofo de la Ilustración) en 1801. Recordemos que esto es época de la Revolución Francesa (todo tiene que ver con todo, ¿no?).

Detengámonos en esto un momento y concienticemos: el término "ideología" fue inventado, de la nada por una persona. Antes de 1801 nadie había formulado ni el término, ni la idea.

Hagamos fast-forward hasta 1845 (casi 50 años después): Karl Marx y Friedrich Engels, resignifican el término en su obra "La ideología alemana"). Para ellos "ideología" es (según Wikipedia) "el conjunto de principios que explican el mundo en cada sociedad en función de sus modos de producción, relacionando los conocimientos prácticos necesarios para la vida con el sistema de relaciones sociales; la relación con la realidad es tan importante mantener esas relaciones sociales, y en los sistemas sociales en los que se da alguna clase de explotación, evitar que los oprimidos perciban su estado de opresión."

Wow. ¿Soy yo o es una definición de una complejidad extraordinaria? A mí lo que me parece más interesante es que es una definición definitivamente "filosófica", más que "política". Es decir, es filosófica y política a la vez, pero no en cantidades iguales.

A lo que quiero ir con todo esto es que, así como estos pensadores definieron esas ideologías, un pensador hoy podría definir una ideología nueva. De hecho un montón de gente no se siente alineado con ninguna ideología en particular, sino simplemente un conjunto de ideas y valores generales que pueden derivarse de la [Regla de oro](https://es.wikipedia.org/wiki/Regla_de_oro_(%C3%A9tica)).

## Así como las ideologías existen, las ideologías no existen

Este libro no se apega a ninguna ideología porque no le encuentra sentido ni utilidad en el mundo actual. Las ideologías per-se o puras ya no existen. Fueron un conjunto de ideas filosóficas, psicológicas y sociales que en algún momento de la historia pueden haber sido utiles para congregar a las masas en grupos concretos (capitalismo vs comunismo por ejemplo). (Otro problema de las "ideologías" es que pueden fácilmente ser utilizadas como medio de manipulación de las masas.)

Aún así hay gente que necesita un encuadre ideológico para sumarse a un proyecto, como decíamos arriba en ese caso el encuadre sería el de la [Regla de oro](https://es.wikipedia.org/wiki/Regla_de_oro_(%C3%A9tica)):

> Un principio moral general que puede expresarse: «trata a los demás como querrías que te trataran a ti» (en su forma positiva) o «no hagas a los demás lo que no quieras que te hagan a ti» (en su forma negativa, en esta forma también conocida como regla de plata). No consiste en la afirmación de determinadas conductas o en la imposición de valores afirmativos o positivos, como sucede en las doctrinas dogmáticas, sino que preconiza una dinámica de relaciones intersubjetivas basada en el sentido común y en el principio de no agresión.

> Su universalidad sugiere que puede estar relacionada con aspectos innatos de la naturaleza humana. Quien la aplique tratará con consideración a todos los seres humanos, y no solo a miembros de su grupo. Se considera a la regla de oro el punto de partida para la reflexión teórica y el proceso histórico que condujo a la formulación de los derechos humanos; aunque identificar ambos conceptos es anacrónico.

Como dato curioso, esta idea de usar la Regla de Oro para definir cuestiones políticas y sociales no es nueva:

> John Locke propuso los derechos a «la vida, la libertad y la propiedad». Para Locke, el propio cuerpo es parte de los bienes de un hombre y, por tanto, sobre él se ejerce un derecho a la propiedad que teóricamente garantiza la seguridad de las personas al igual que la de sus posesiones. Posteriormente, este concepto fue recogido por la Ilustración y el pensamiento democrático posterior a la Revolución francesa

Así, entonces, creemos que, ante todo, el primer punto en común que necesita esta solución ciudadana es el expresado en estas palabras. Algunas citas más que expanden este concepto:

> George Bernard Shaw (1898) estableció una evidente precaución a la aplicación de la regla de oro en sentido activo o positivo: «no hagas a otros lo que quisieras que te hagan a ti. Sus gustos pueden no ser los mismos»

> El filósofo alemán Hans Reiner (1896-1991) distinguía diferentes formulaciones de la regla de oro: la regla de empatía, que parte de nuestros deseos o temores («lo que tú mismo temas, no lo hagas a los demás, lo que deseas para ti, hazlo a los demás»), y la regla de la equidad, que parte de nuestros juicios de valor («lo que reprochas a otros, no lo hagas tú mismo; debes actuar como juzgas que los demás deben hacerlo»)

> Thomas Nagel (1970) propuso repensar el altruismo de forma objetiva sobre la base de la ética de la reciprocidad

> En los años 1990, Enno Winkler desarrolló un código de ética universal en el que la regla de oro está incluido como un mandamiento para las relaciones interpersonales en ausencia de empatía: «¡Respeta al otro como a ti mismo!».

