--- 
title: "País Ciudadano"
author: "loqesangra"
date: "`r Sys.Date()`"
site: bookdown::bookdown_site
output: bookdown::gitbook
documentclass: book
bibliography: [book.bib, packages.bib]
biblio-style: apalike
link-citations: yes
github-repo: loqesangra/pais-ciudadano
description: "País Ciudadano es un libro de texto open-source, online, ciudadano y participativo, con el objetivo de definir y modelar un modelo de país en manos de la ciudadanía, y a la vez señalar y denunciar las falencias del status quo."
---

# Declaración de principios

País Ciudadano es un libro:

- Open Source
- Online
- Ciudadano
- Participativo

El objetivo es tener una referencia online multidisciplinaria de un modelo de país que todavía no se ha pensado. Si los fundadores de las patrias modernas hubieran tenido las herramientas que tenemos hoy, ¿habrían fundado los países tal y como los conocemos?

## Lineamientos

- El libro no es de nadie y es de tod\@s a la vez
- La colaboración esta abierta a cualquiera que quiera aportar
- Será a la vez un espacio político sin chicanas políticas
- Será una fuente de conocimiento y referencia para el presente y el futuro
- Será una fuente de educación al explicar y mostrar procesos y metodologías de trabajo que pueden aplicarse en otras áreas
- Será un lugar limpio de la toxicidad reinante en redes sociales y otras plataformas


## Hashtag

Desde ya que además de los objetivos planteados este proyecto tiene la esperanza de impactar la realidad en algún momento. Se alienta el uso del hashtag **#paisciudadano** en las redes para referirse y comunicar sobre el proyecto. Con el solo hecho de compartir, ya estás colaborando. Inundemos las redes sociales para desperdigar este mensaje.

Se espera que los mensajes generados en redes sociales con este hashtag se abstengan a los siguientes "Valores y reglas de estilo y conducta":

## Valores y conducta

Inspiradas por la [Reddiqueta](https://www.reddit.com/wiki/es/reddiquette) o [Reddiquette](https://reddit.zendesk.com/hc/en-us/articles/205926439-Reddiquette).

- Recordá que quien lee lo que escribís es un ser humano
- Comportate en internet como te comportarías en la vida real
- Leé las reglas antes de colaborar
- Leé la documentación proveída, para algo está
- La moderación se hará con respecto a la calidad del contenido, no a las opiniones
- Las opiniones deberán exponerse desde un lugar individual, apartidario y fáctico en la medida de lo posible
- Usa la gramática y la ortografía correctamente. Se permiten deformaciones del lenguaje siempre y cuando estén en función de la comunicación.
- Es obligatorio citar fuentes si estás utilizando algún recurso externo
- Las críticas deben ser constructivas
- Tratemos de conservar la buena onda. Para mala onda ya es suficiente con la realidad.

Ver "Código de Conducta" para una expansión respecto a estos conceptos.

## Cómo colaborar

Una de las iniciativas será escribir una guía para que cualquiera sin conocimientos en desarrollo web, programación o cualquiera de las tecnologías utilizadas por este libro pueda hacerlo. Por el momento la única referencia con respecto a como colaborar será el proyecto original: https://github.com/rstudio/bookdown.

Si pasás por acá y querés ayudarme por ahora por favor escribime a loqesangra@gmail.com. Algo para hacer te voy a pasar, seguro.

El libro y proyecto es abierto y público en todo sentido. No se pretende tener ninguna línea editorial ni bajada de línea de ningún tipo. Así mismo su propia estructura irá modificándose y siendo maleable con el tiempo.

## Lo que más necesita este proyecto en este momento

- Colaboradores de cualquier tipo
- Ayuda editorial para definir mejor los contenidos y lineamientos
- Algún tipo de gerencia de proyecto para definir prioridades y roadmap
- Ayuda técnica para lidiar con las herramientas tecnológicas

## Posibles capítulos y temáticas a ser escritas

Sin ningún orden particular, ideas aleatorias de desarrollo para el proyecto, desde ya y sin temor a repetir, el proyecto necesita tu ayuda para llevar a cabo todo esto:

Posibles textos o capítulos:

- Un Estado
  - Contenidos de qué debería tener un estado ideal, de qué es lo que se está haciendo bien y qué mal
- Desarmar la radicalización de los discursos existentes explicar que cualquier partido político que se endilgue la potestad de ser "la solución" a determinada realidad está equivocado, ya que no hay soluciones absolutas ni contextos fijos
- Fomentar el respeto y la inclusión por los demás
- Individualismo y colectivismo (por qué necesitamos de los dos, del desarrollo individual y del desarrollo colectivo)
- Lo importante de tener foco para progresar en algo, de tener metas a largo y corto plazo y cómo esto mismo aplica a los países
- Corrupción y transparencia
  - ¿El gran problema? Definitivamente no el único, pero es uno de los más grandes? Es una urgencia que se tiene que desarmar ya. No podemos permitir más corrupción. Cómo se evita? Con herramientas transparentes. Hoy el mundo online nos permite tener estas herramientas. Este proyecto es un ejemplo de transparencia.
- Permeabilidad
  - cómo las instituciones, constituciones y leyes clásicas ya son algo anacrónico y podemos modernizarlas
- Ideologías
  - fueron funcionales en un momento de la historia, centrémonos en la libertad y el respeto por el otro (después veremos cómo esto aplica o no aplica a la economía)
- Redes sociales y su uso
  - cómo estamos perdiendo tiempo todos discutiendo por TW, Reddit, IG, etc, etc, en vez de generar contenido de valor que podría estar cambiando el curso de la historia
- Tecnología y su uso y abuso
- Revisar y reflexionar sobre palabras y términos que se usan con una soltura e ignorancia absolutas, generando confusión en la ciudadanía
- Análisis de los modelos de Estado actuales y en qué podrían ser más eficientes (y cómo, definir procesos, etc)
- Recursos de educación financiera adaptados a las realidades y posibilidades de cada un@
