# Introducción y resumen general {#intro}

Se hace largo leer hoy en día, lo sabemos. Pero por favor, tomate 5 minutos y leé todo esto.

Entre tantas maravillas que han podido crear los seres humanos a lo largo de su historia una de ellas es, sin lugar a dudas, la escritura. Los libros, las palabras, los discursos, han movido el curso de La Historia.

La política actual se ha apuntalado a base de discursos y palabras. Cuando debería ser al revés, res non verba (hechos, no palabras).

**Necesitamos un discurso centralizado, político pero apartidario, donde diversas fuerzas ciudadanas, individuales y colectivas, puedan encontrar puntos de encuentro.**

Este libro pretende ser eso (es abierto, público y colaborativo - ver [Declaración de Principios]).

Este proyecto es encarado con la solemnidad histórica que ha tenido cualquier libro que se precie de serlo, y a la vez, eleva aún más la vara: en estos tiempos donde evolucionamos de manera exponencial, un libro impreso queda anticuado en el preciso momento en que la tinta empapa el papel. Por eso este libro es un organismo vivo. Alguna versión del mismo podrá ser impresa pero en su base **País Ciudadano es un libro Vivo, Libre y Participativo, en constante transformación.**

Esta idea de un "libro vivo" no es nueva y ya se ha implementado exitosamente, algunos ejemplos:

- https://hybridpedagogy.org/#publishing
- https://geocompr.github.io/user_19/presentation/#1
- https://geocompr.robinlovelace.net/

## Qué anda pasando (Status quo)

> "Status quo:" expresión latina con que se hace referencia al estado o situación de ciertas cosas, como la economía, las relaciones sociales o la cultura, en un lugar y momentos determinados.

El "lugar y momento determinado" de estas palabras es Argentina 2021 (en la medida en que se sumen colaboradores podrá este análisis expandir sus fronteras).

Estamos convencidos de que hay una Crisis Institucional y de Representatividad. Trataremos de explayarnos sobre esta idea pero por ahora la base es la siguiente: todos los países tienen problemas diferentes. Pero hay un problema que es común a todos y es precisamente esta Crisis.

La teoría sobre la que se va a basar este libro es: **la causa de gran parte de los problemas reinantes en las sociedades actuales se pueden extrapolar, en la mayoría de los casos, a una crisis institucional y de representatividad**. Esta idea no es nueva y pueden citarse múltiples referencias académicas de la misma. (ejemplo: https://revista-estudios.revistas.deusto.es/article/view/239/376)


## Crisis Institucional y de Representatividad

¿A qué nos referimos con esto? A una idea muy simple. Tan simple que repasando esta definición de Democracia se puede ver:

> La democracia (del latín tardío democratĭa, y este del griego δημοκρατία dēmokratía) es una manera de organización social que atribuye la titularidad del poder al conjunto de la ciudadanía. En sentido estricto, la democracia es una forma de organización del Estado en la cual las decisiones colectivas son adoptadas por el pueblo mediante mecanismos de participación directa o indirecta que confieren legitimidad a sus representantes. En sentido amplio, democracia es una forma de convivencia social en la que los miembros son libres e iguales y las relaciones sociales se establecen conforme a mecanismos contractuales.

La Crisis Está porque La Democracia No Está. **La Democracia está rota en su implementación**. Hoy la "Democracia" no le otorga la titularidad del poder al conjunto de la ciudadanía. En repetidos países de todo el mundo los mecanismos de participación directa o indirecta que deberían conferir legitimidad a sus represantes, no están cumpliendo ese objetivo.

Hoy en día "los representantes" del pueblo no responden a los intereses del pueblo; responden a los intereses de las grandes concentraciones de poder (fuerzas económicas, corporativas, de comunicación, sociales).

¿Y por qué pasa esto? Porque **el Modelo de Instituciones que tenemos quedó anticuado y tiene muchos problemas y huecos en su ejecución** que permiten manejos espurios, malversación de fondos públicos, manipulación del discurso público, corrupción de todos los tipos, etc.


## La solución

Habiendo coincidido en que la Crisis Institucional y de Representatividad es el gran problema de este siglo, es fácil inferir que la solución entonces pasa por una reformulación absoluta de Nuestras Instituciones, la forma en que funcionan, la forma de gobierno incluso: una reformulación de todo el status quo.

Tenemos que entender que la forma en que gobernamos y nuestro sistema de gobierno son "nuestros" (de la ciudadanía) de manera literal: la ciudadanía define la forma en que se gobierna, la ciudadanía tiene en sus manos arreglar el sistema de gobierno que está roto.

Los ciudadanos podemos y debemos impactar en nuestra realidad. Ya estamos todos cansados. Ya estamos todos en las calles. Falta esta vuelta de rosca. Replantear nuestras instituciones.

La solución a nuestros problemas no pasa por discutir cada vez más y más violentamente, la solución a nuestros problemas no pasa por ver quién tiene razón, la solución a nuestros problemas no pasa por los extremos, la solución a nuestros problemas no pasa por individuos o ideologías.

La solución a nuestros problemas pasa por intercambiar ideas pacíficamente, por sacarse las camisetas políticas y discutir planes de acción, por entender que no hace falta ver quién tiene razón si podemos comprobarlo con estadísticas y datos, por entender que acercándonos y no alejándonos vamos a lograr consenso, por entender que tenemos que hacerlo todos juntos, unidos como sociedad en la medida de lo posible, y entendiendo que, justamente, como la definición de arriba dice:

**Podemos construir Una Democracia (o Forma de Gobierno) donde realmente se genere una convivencia social y pacífica en la que los miembros sean libres e iguales (iguales ante La Forma, entendiendo que a la vez Somos Únicos y Diferentes) y las relaciones sociales se establezcan conforme a mecanismos contractuales**.

## Cómo llevar a la práctica esa solución

Hace no tantos años un proyecto de esta magnitud requeriría años de planeamiento, muchísimo dinero atrás, etc. El encuadre clásico sería formar un partido político y hacerlo andar.

Hoy en día tenemos la tecnología necesaria para:

- juntar una gran masa crítica detrás de una iniciativa
- plantear las modificaciones institucionales que sean necesarias
- auditar al gobierno y todos sus miembros
- auditar al Estado y su funcionamiento
- acercar a la realidad esa idea de "gobierno de la multitud" como decía Platón o "gobierno de los más" como decía Aristóteles

Cuando caés en la cuenta de que el sistema de gobierno que utilizamos hoy nació en el siglo XVIII con las revoluciones francesa y estadounidense te cae la ficha.

¿Somos concientes de esto? Nuestro sistema de gobierno fue pensado en el año 1780 aproximadamente.

Hace 240 años.

**Es hora de repensar cómo gobernamos. Es hora de que una vez más la ciudadanía se haga cargo de su destino**.

Esta vez, a diferencia de muchos otros momentos de la historia, podemos hacerlo pacíficamente apalancando las herramientas tecnológicas que ya tenemos en nuestro poder.

**De eso se trata #paísciudadano**. Esta iniciativa que por el momento tiene forma de libro.

Podría ser mucho más.






