# Partidos políticos

Así como veíamos con el análisis de [Ideología] (concepto inventado hace no tantos años) algo similar pasa con los partidos políticos. El concepto moderno de partido político aparece en la Gran Bretaña del siglo XIX (año 1800 y pico), con el "Partido Conservador y Unionista" y el "Partido Liberal". No es casual que esta separación entre "conservadores" y "liberales" nos suene conocida. Pero vamos a ahondar un poco más respecto a qué vendría ser cada cosa.

## Conservadores

¿A qué nos referimos cuando hablamos de política y decimos "conservadores"? Es un concepto simple descrito por la propia palabra: un partido político conservador es un partido político que quiere conservar el estado de las cosas. En sus orígenes, los partidos conservadores buscaban preservar los privilegios de los grupos de poder, especialmente de las monarquías y aristocracias.

## Liberales

¿A qué nos referimos cuando hablamos de política y decimos "liberales"? Acá es interesante ahondar un poco más en el concepto de Liberalismo y quizás pueda escribirse un capítulo entero al respecto. Lo importante por ahora es, no confundir Liberalismo con:

-   Neoliberalismo

-   Libertarianismo

Volviendo a nuestra breve historia sobre partidos políticos, los "liberales" se presentan como la contracara de los "conservadores". Surje como fuerza política de la burguesía (fuerza social en puja, recordemos que estamos en los \~1800, apenas unos años después de la Revolución Estadounidense de 1776 y la Revolución Francesa en 1789 justamente llevadas a cabo por las burguesías de ambos países).

## Partidos políticos en la actualidad, ¿son necesarios?

Ni sí, ni no. Desde este libro creemos que ya no son necesarios, pero desde ya que no estamos en contra de ningún partido político. Al fin y al cabo son organizaciones sociales en su concepción (como puede serlo un club o un sindicato).

Consideramos que el problema de los partidos políticos actuales es que han olvidado su vocación de servicio a la comunidad y se han convertido en simplemente actores en una puja de poder que está lejos de implicar a la ciudadanía.

## Partidos políticos y religión

Algunos artículos (buscar referencias) afirman que a nivel global las religiones están perdiendo adeptos. Y esos adeptos están depositando "su fe" en los partidos políticos.

Es fácil entender lo peligroso que es "creer" en un partido político. Y es también fácil ver cómo el comportamiento social encolumnado detrás de partidos políticos actúa de manera similar a las religiones.

Los partidos políticos se han convertido en una "pasión" (y esto no es casual, la manera de comunicarse de un partido político alienta esta idea, su marketing y comunicación tienen un "lenguaje" común, un estilo, frases hechas comunes, etc).

Por esto desde este libro creemos fervientemente que la solución política no pasa por los partidos políticos. La ciudadanía también puede hacer política en su conjunto, sin la necesidad de alinearse detrás de un partido político.

Consideramos que no podemos pretender que un partido político sea la solución a nuestros problemas. La solución a nuestros problemas depende de nosotros los ciudadanos, y no de un partido político.

Posibles expansiones para el capítulo:

-   Ahondar en cómo funcionan los partidos políticos

-   Cómo se financia un partido político

-   Luchas de poder

-   Historia de los partidos políticos en Argentina

-   Comparación de programas de los partidos políticos

-   Análisis del discurso

-   etc
