# El precedente: Doc Para El País

Esta idea viene rondando en mi cabeza hace rato ya. Tomó forma de Movimiento, Revolución, ONG y ahora de Libro.

Finalmente, todo se trata de Palabras.

Lo irónico es que encarando esta idea del Libro hoy, 6 de Mayo de 2021, mi cabeza me lleva instantáneamente al "Doc Para El País" que empecé a escribir en Marzo 2021 y nunca terminé. El título del siguiente apartado, "Documento para el Desarme Argentino", es precisamente el título con el cual arrancaba ese Doc.

Si bien el "Doc Para El País" era una iniciativa similar a País Ciudadano, no funcionó porque a) no seguí trabajándolo y b) carecía de un encuadre y modo de trabajo comunitario. País Ciudadano es la versión evolucionada de "Doc Para El País".

Este capítulo reproduce las palabras escritas en el mencionado doc allá por Marzo de 2021 considerando que son relevantes y dan contexto a País Ciudadano también.

> Importante: "Doc Para El País" empezó siendo un proyecto "Argentino" y por eso hace referencia a esta Nación. País Ciudadano no pretende enarbolar la bandera de ningún país en particular, y está convencido que la crisis de representatividad que vivimos es mundial. Las instituciones que el mundo ha venido usando hasta el momento ya no le sirven a la ciudadanía y se necesita un cambio. Por eso este proyecto no será sobre "Argentina" sino sobre El Mundo.

## Documento para el Desarme Argentino

¿Hay alguien que no esté cansado de vivir así como vivimos en Argentina 2021? ¿Hay alguien que diga "qué hermoso país, tal cual así como está, está perfecto, no hay nada por hacer"?

Yo creo que no. Pero bueno, afirmarlo sería pretender el Absoluto. 

---

Lo que te quiero decir es que, como chabón racional que soy, pienso mucho en las posibilidades. En el concepto general de posibilidad. O quizás en el concepto de estadística, no estoy seguro. A lo que voy es a esto: **es muy importante para todo lo que va a decir este documento**, que pensemos en el concepto de Infinito. Acordate también que **yo de todo esto no sé NADA, solo escribo palabras lindas. Hay que escuchar a la gente que estudia**. Para algo estudia. Lo mío son solo ideas sueltas. Los cabosideas sueltes les tenemos que atar entre todos.

Bueno, Infinito entonces. ¿Qué es el Infinito? ¿Es "el"? ¿Es una cosa El Infinito? Mirá, me gusta escribirlo con mayúsculas. Porque cuando escribís cosas con mayúsculas es como que de repente Son Importantes. Es Importante El Infinito. O por lo menos El Concepto De Infinito.

Me fui al Infinito y Más Allá. Tenemos entonces: Posibilidades, Estadística, Infinito. Acá voy: **¿las posibilidades de que algo suceda en la mismísima infinitud del Universo, algo, cualquier cosa, son infinitas?**

tati.gonzalez1 dice "yo creo que las cosas pasan por la fuerza del mismo universo" me gustó
pia.constanzo dice que hay una frase: "el universo siempre conspira a mi favor"

Entiendo que sí. Que alguien me ayude con la bibliografía pero debe ser así: **las posibilidades de que algo, un evento cualquiera suceda, son Infinitas**.

Entonces, partiendo de esa afirmación, ¿podemos decir que existen posibilidades de que Argentina cambie? Sí. Es la única respuesta a esa pregunta, siguiendo la línea de pensamiento que venimos trayendo.

Entonces. Esa es la línea de pensamiento que tenés que tener mientras leés este documento. **Tu mente tiene que ser una esponja seca hundida en el agua de la bañera**, viste esas de supermercado, que tienen un color suavecito y las hundís en el agua y se oscurecen, se empapan completas, PESAN, CHORREAN AGUA. **En ese estado tu mente tiene que vivir. Tu mente tiene que estar permeable a nuevas ideas**, y en parte para lograr eso ¿sabés qué tenés que hacer? **Tenés que cuestionar tus propias ideas**. No te digo todo el tiempo, porque sino te volvés locx y terminás siendo un inconsistente de m****. Pero sí, de vez en cuando, subilas al ring a tus ideas. A ver si se la aguantan.

Esto claramente interpela a la enorme mayoría que hoy en día "banca" a cualquiera de los dos partidos políticos dominantes. Que voy a llamar A y B. Para ser lo más imparcial posible. **No importan los partidos políticos**. Que quede claro, hablo desde un lugar completamente apartidario. Ni siquiera me gusta la política, hablo, hago y soy política en principio porque soy ciudadano - un ciudadano del sistema inevitablemente es un ser político. Hago todo esto para vivir una vida tranquila. Porque estoy convencido que es el camino. Si no lo hago, no voy a vivir tranquilo. ¿Vos, vivís tranquilx?

Volvamos entonces.

Argentina, puede cambiar.

Es un hecho demostrado por la ciencia. (check)

Habiendo acordado eso, arranquemos esto.

## Argentina Puede Cambiar

Yo leo "Argentina Puede Cambiar" y francamente pienso en un libro de autoayuda. Y a veces cuando escribo y digo estas cosas onda "tú puedes" siento lo mismo: pero carajo, estoy escribiendo un libro de autoayuda! Eso escribí y me fui a googlear sobre "autoayuda". Lo loco es que hasta acá vengo diciendo "autoayuda" de una manera un poco despectiva, por si no se sintió. Quiero ser transparente al respecto.

Pero este es el punto: haberlo escrito me hizo dar cuenta que yo estaba hasta recién prejuzgando el concepto de "autoayuda". Banalizándolo, por decirlo de alguna manera.

Pero el punto de todo esto es que está mal. Está mal prejuzgar. Están mal los preconceptos. ¿Cuántas veces te pasó que tenías una idea y de repente, la cambiás completamente en un instante? Es como ese decir de "tener un click", algo, un cambio de rumbo, algo que se dispara en tu vida, en tu cabeza, o algo externo te lo dispara, lo que fuera, y cambiaste.

Y quizás nunca te pasó, y también está bien. Esta indefinición es todo lo hermoso que tiene la vida, y a la vez toda la mierda que tiene. La vida puede ser absolutamente cualquier cosa y ese infinito es hermoso y aterrador a la vez.

Argentinos: (escribo "Argentinos:" y ya pienso en populismo y en todo lo malo que le han hecho a nuestra nación - escribo "populismo" y ya pienso que alguien podría estar ubicándome a "la derecha" de cierto espectro político que aún creemos que existe pero no sabemos bien para qué si sirve o si, sirve para algo en absoluto - pero no importa, quedate conmigo, leeme un poco más, todas estas son las ideas que vengo a combatir - pacíficamente. Siempre pacíficamente.)

Argentinos: Argentina Puede Cambiar.

Podemos cambiar el país. No soy macrista ni kirchnerista. Solo soy un ciudadano argentino escribiendo lo que piensa y pidiendo que sus co-ciudadanos se congreguen de manera pacífica a pensar juntos. Pensemos todos juntos.

Pensemos en cuál es el país que queremos.

Y así, lo vamos a tener.

## Cómo Cambiar

Claro ponele que hasta acá me compraste la idea. Si no me la compraste comuniquémonos que lo hablamos juntos y me contás qué parte no te convence. Estoy convencido de que hablando se entiende la gente. Con esa premisa te pregunto: ¿creés en que la infalible manera de avanzar en la vida es: hablando, comunicando lo que sentimos, tratando de no enojarnos, tratando de que las emociones no nos dominen - pero a la vez, de que los pensamientos tampoco nos dominen, y respetando a los demás? Yo creo que sí.

Creo que la violencia no es solución a nada. Es un imposible, pero imaginate poder hacer un estudio serio y estadístico de los actos de violencia que han sucedido en la historia del mundo y en la historia de la humanidad y probablemente el resultado sea que lo único que hizo cualquier tipo de violencia fue generar más violencia.

Cuando te tiran con violencia es muy jodido responder con paz. La violencia genera sentimientos oscuros en lo profundo de uno y la respuesta instintiva es responder con la misma violencia, o más, para ganar.

Pero bueno, el subtítulo de esta sección dice "Como Cambiar". Eso es lo segundo que se te viene a la cabeza cuando caés en la cuenta de que Argentina Puede Cambiar. Bueno, este Doc pretende ser un poco eso. Una guía, unas ideas, abrir la cabeza y pensar en Cómo la Argentina Puede Cambiar, qué cosas podrían hacerse, eliminar los "peros" uno por uno - llegar a un consenso real y lo más justo posible - para esto vamos a tener que filosofar un poco, pero ya te dije que soy muy racional y amante de los datos y estadísticas, así que todo lo que podamos "medir" lo vamos a medir. Todo lo que sea medible hay que medirlo y sacar conclusiones en base a eso. Sin invadir la privacidad de nadie, desde ya. Es como ser una esponja de realidad. La "Big Data" nos ayuda a ser esponjas de una realidad pocas veces fácil de absorber.



